install:
  - pip install pycodestyle octoprint

jobs:
  allow_failures:
    - language: node
      node_js: lts/*
      script:
        - npm install eslint --save-dev
        - eslint octoprint_youtube_timelapse
  include:
    - language: python
      python: 3.9
      script:
        - pycodestyle . --exclude venv,setup.py --ignore=E501
    - language: python
      python: 3.9
      script:
        - pip install -r requirements.txt
        - octoprint dev plugin:install
